storage:
  image: ubuntu:14.04
  volumes:
    - /storage

db:
  image: postgres:9.3


broker:
  image: rabbitmq:3.5
  command: /usr/lib/rabbitmq/lib/rabbitmq_server-3.5.0/sbin/rabbitmq-server


worker:
  build: .
  command: celery worker -A rodrigues -l INFO
  links:
    - broker
    - db
  environment:
    - DJANGO_SETTINGS_MODULE=rodrigues.settings.container
    - SECRET_KEY="doesn't matter"
    - SERVER_NAME
    - DEBUG
    - SERVER_EMAIL
    - EMAIL_PORT
    - EMAIL_HOST
    - EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD
  volumes:
    - /var/run/docker.pid:/var/run/docker.pid
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker:/var/lib/docker
    - .:/code
  volumes_from:
    - storage

django:
  build: .
  command: uwsgi --socket /socket/rodrigues.sock --module rodrigues.wsgi --chmod-socket=666
  links:
    - db
    - broker
  environment:
    - DJANGO_SETTINGS_MODULE=rodrigues.settings.container
    - SECRET_KEY
    - SERVER_NAME
    - CYBERSKA_URI
    - DEBUG
    - SERVER_EMAIL
    - EMAIL_PORT
    - EMAIL_HOST
    - EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD
  volumes:
    - .:/code
    - /socket
  volumes_from:
    - storage


skaviewer:
  image: radioastro/cyberska_viewer
  volumes_from:
    - worker
    - storage
  environment:
    - SERVER_NAME
    - REDIRECT_URI
  volumes:
    - pureweb.lic:/opt/CSI/PureWeb/Server/conf/pureweb.lic
  ports:
    - 8081:80
    - 8080:8080



nginx:
  image: nginx:latest
  volumes:
    - nginx.conf:/etc/nginx/nginx.conf:ro
    - ssl.crt:/etc/nginx/ssl.crt:ro
    - ssl.key:/etc/nginx/ssl.key:ro
  volumes_from:
    - django
  links:
    - skaviewer
  ports:
    - 80:80
    - 443:443 


