storage:
  image: ubuntu:14.04
  volumes:
    - /storage

db:
  image: postgres:9.3


broker:
  image: dockerfile/rabbitmq


worker:
  build: .
  command: celery worker -A rodrigues -l INFO
  links:
    - broker
    - db
  environment:
    - DJANGO_SETTINGS_MODULE=rodrigues.settings.container
    - SECRET_KEY="doesn't matter"
  volumes:
    - /var/run/docker.pid:/var/run/docker.pid
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/docker:/var/lib/docker
    - .:/code
  volumes_from:
    - storage


django:
  build: .
  command: uwsgi --socket /socket/rodrigues.sock --module rodrigues.wsgi --chmod-socket=666
  links:
    - db
    - broker
  environment:
    - DJANGO_SETTINGS_MODULE=rodrigues.settings.container
    - SECRET_KEY="change this by defining SECRET_KEY env var"
    - ALLOWED_HOST
    - CYBERSKA_URI
    - ADMIN_EMAIL
    - DEBUG
    - EMAIL_HOST_USER
    - EMAIL_HOST_PASSWORD
  volumes:
    - .:/code
    - /socket
  volumes_from:
    - worker
    - storage


skaviewer:
  image: gijzelaerr/cyberska_viewer
  volumes_from:
    - worker
    - storage
  environment:
    - REDIRECT_URI
  volumes:
    - pureweb.lic:/opt/CSI/PureWeb/Server/conf/pureweb.lic
  ports:
    - 8081:80
    - 8080:8080



nginx:
  image: nginx:latest
  volumes:
    - nginx.conf:/etc/nginx/nginx.conf:ro
  volumes_from:
    - django
  links:
    - skaviewer
  ports:
    - 80:80 


