# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('name', models.CharField(default='New simulation', max_length=200)),
                ('observatory', models.CharField(default='MK', choices=[('MK', 'MeerKAT'), ('K7', 'KAT-7'), ('JA', 'JVLA-A')], max_length=32)),
                ('output', models.CharField(default='I', choices=[('I', 'Image'), ('V', 'Visibilities')], max_length=1, verbose_name='Output type')),
                ('sefd', models.FloatField(null=True, blank=True, verbose_name='SEFD', help_text='System defaults will be used if left blank')),
                ('sky_type', models.CharField(default='T', choices=[('T', 'Tigger-LSM'), ('A', 'ASCII'), ('F', 'FITS'), ('S', 'KATALOG')], max_length=1)),
                ('sky_model', models.FileField(upload_to='sky', blank=True)),
                ('katalog_id', models.CharField(default='NV', verbose_name='KATALOG', max_length=64, help_text='Choose from our sky catalogs', choices=[('NV', 'nvss6deg'), ('S3', 'scubed1deg'), ('K3', '3c147_field'), ('K4', '3c147_field_no_core')], blank=True)),
                ('radius', models.FloatField(help_text='Radius of degrees', default=0.5, verbose_name='Radius', blank=True)),
                ('fluxrange', models.CharField(help_text='Flux range in Jy', default='0.001-1', max_length=32, verbose_name='Flux range')),
                ('ms_dec', models.CharField(help_text='in dms', default='-30d0m0s', max_length=32, verbose_name='Declination')),
                ('ms_ra', models.CharField(help_text='in hms', default='0h0m0s', max_length=32, verbose_name='Right ascension')),
                ('add_noise', models.BooleanField(default=True)),
                ('vis_noise_std', models.FloatField(help_text='Generates from SEFD if 0', default=0, verbose_name='Visibility noise std')),
                ('ms_hours', models.FloatField(help_text='in hours', default=0.25, verbose_name='Synthesis time')),
                ('ms_start_time', models.FloatField(help_text='in hours', default=-0.125, verbose_name='Initial hour angle')),
                ('ms_dtime', models.IntegerField(help_text='in seconds', default=10, verbose_name='Integration time')),
                ('ms_freq0', models.FloatField(help_text='in MHz', default=700, verbose_name='Start frequency')),
                ('ms_dfreq', models.FloatField(help_text='in kHz', default=50000.0, verbose_name='Channel width')),
                ('ms_nchan', models.IntegerField(help_text='Number of frequency channels per band', default=1, verbose_name='Channels per band')),
                ('ds_amp_phase_gains', models.FloatField(default=1, verbose_name='Amplitude Phase Gains')),
                ('ds_parallactic_angle_rotation', models.BooleanField(default=True, verbose_name='Parallactic Angle Rotation')),
                ('ds_primary_beam', models.CharField(default='M', choices=[('M', 'MeerKAT-1'), ('N', 'MeerKAT-2'), ('O', 'MeerKAT-3'), ('K', 'KAT-7'), ('W', 'WSRT'), ('J', 'JVLA')], max_length=1)),
                ('ds_feed_angle', models.FloatField(default=0, verbose_name='Feed angle')),
                ('cr_amp_phase_gains', models.FloatField(default=1, verbose_name='Amplitude Phase Gains')),
                ('cr_pointing_error', models.FloatField(default=0)),
                ('cr_rfi', models.FloatField(default=0)),
                ('imager', models.CharField(default='LW', choices=[('LW', 'LWIMAGER'), ('WS', 'WSCLEAN'), ('CA', 'CASA')], max_length=32, verbose_name='Imager')),
                ('im_npix', models.IntegerField(help_text='in pixels', default=512, verbose_name='Image size')),
                ('im_cellsize', models.FloatField(help_text='in arcseconds', default=1, verbose_name='Pixel size')),
                ('im_weight', models.CharField(default='N', choices=[('N', 'Natural'), ('U', 'Uniform'), ('B', 'Briggs')], max_length=1, verbose_name='uv-Weighting')),
                ('im_robust', models.FloatField(help_text='Briggs robust parameter', default=0, verbose_name='Robust')),
                ('im_weight_fov', models.FloatField(null=True, blank=True, verbose_name='Weight FoV', help_text='in arcminutes')),
                ('im_wprojplanes', models.IntegerField(default=0, verbose_name='w-Projection planes')),
                ('im_mode', models.CharField(default='C', choices=[('C', 'channel'), ('M', 'mfs'), ('V', 'velocity'), ('F', 'frequency')], max_length=1, verbose_name='Imaging mode')),
                ('im_spwid', models.CharField(default=0, max_length=32, verbose_name='Spectral window')),
                ('channelise', models.FloatField(help_text='0 means average all, 1 per channel, etc.', default=0, verbose_name='Image channelise')),
                ('im_stokes', models.CharField(default='I', max_length=4, verbose_name='Stokes')),
                ('make_psf', models.BooleanField(default=True, verbose_name='Make PSF')),
                ('lwimager', models.BooleanField(default=False, verbose_name='Deconvolve with me!')),
                ('lwimager_niter', models.IntegerField(default=1000, verbose_name='NITER')),
                ('lwimager_gain', models.FloatField(default=0.1, verbose_name='Loop gain')),
                ('lwimager_threshold', models.FloatField(help_text='In Jy', default=0, verbose_name='Clean Threshold')),
                ('lwimager_operation', models.CharField(default='C', choices=[('C', 'csclean'), ('H', 'hogbom'), ('D', 'clark'), ('M', 'multiscale')], max_length=32, verbose_name='Clean algorithm')),
                ('lwimager_cyclefactor', models.FloatField(default=1.5, verbose_name='Cycle factor')),
                ('lwimager_cyclespeedup', models.FloatField(default=-1, verbose_name='Cycle speed up')),
                ('lwimager_stoppointmode', models.FloatField(default=-1, verbose_name='Stop point mode,')),
                ('lwimager_nscales', models.IntegerField(default=4, verbose_name='Scales for MS clean')),
                ('lwimager_uservector', models.CharField(null=True, blank=True, max_length=64, verbose_name='Clean scales', help_text='Comma seperated scales in pixels')),
                ('wsclean', models.BooleanField(default=False, verbose_name='Deconvolve with me!')),
                ('wsclean_niter', models.IntegerField(default=1000, verbose_name='NITER')),
                ('wsclean_gain', models.FloatField(default=0.1, verbose_name='Minor loop gain')),
                ('wsclean_mgain', models.FloatField(default=0.1, verbose_name='Major loop gain')),
                ('wsclean_threshold', models.FloatField(help_text='In Jy', default=0, verbose_name='Clean Threshold')),
                ('wsclean_joinpolarizations', models.BooleanField(default=False, verbose_name='Join polarizations')),
                ('wsclean_joinchannels', models.BooleanField(default=False, verbose_name='Join channels')),
                ('wsclean_multiscale', models.BooleanField(default=False, verbose_name='Multiscale clean')),
                ('wsclean_multiscale_dash_threshold_dash_bias', models.FloatField(default=0.7, verbose_name='Multi scale threshold bias')),
                ('wsclean_multiscale_dash_scale_dash_bias', models.FloatField(default=0.6, verbose_name='Multi scale bias')),
                ('wsclean_cleanborder', models.FloatField(help_text='In percentage of image width/height', default=5, verbose_name='Clean border')),
                ('wsclean_smallpsf', models.BooleanField(help_text='Resize the psf to speed up minor clean iterations', default=False, verbose_name='Small PSF')),
                ('wsclean_nonegative', models.BooleanField(help_text='Do not allow negative components during cleaning', default=False, verbose_name='No negative')),
                ('wsclean_stopnegative', models.BooleanField(default=False, verbose_name='Stop on negative')),
                ('wsclean_beamsize', models.CharField(null=True, blank=True, max_length=32, verbose_name='Restoring beam size', help_text='In arcseconds')),
                ('casa', models.BooleanField(default=False, verbose_name='Deconvolve with me!')),
                ('casa_niter', models.IntegerField(default=1000, verbose_name='NITER')),
                ('casa_threshold', models.FloatField(default=0, verbose_name='Threshold')),
                ('casa_gain', models.FloatField(help_text='Clean Loop gain', default='0.1', verbose_name='Loop Gain')),
                ('casa_psfmode', models.CharField(default='CL', choices=[('CL', 'clark'), ('CS', 'clarkstokes'), ('H', 'hogbom')], max_length=32, verbose_name='PSF mode')),
                ('casa_imagermode', models.CharField(default='csclean', choices=[('C', 'csclean'), ('M', 'mosiac')], max_length=32, verbose_name='Imager mode', blank=True)),
                ('casa_gridmode', models.CharField(default='W', verbose_name='Grid mode', max_length=32, help_text='A-projection only works JVLA', choices=[('W', 'widefield'), ('A', 'aprojection')], blank=True)),
                ('casa_nterms', models.IntegerField(help_text='See CASA clean task', default=1, verbose_name='NTERMS')),
                ('casa_reffreq', models.FloatField(null=True, verbose_name='MFS ref Frequency', blank=True)),
                ('casa_multiscale', models.CharField(null=True, blank=True, max_length=200, verbose_name='Multiscale', help_text='Deconvolution scales in pixels')),
                ('casa_negcomponent', models.FloatField(help_text='See CASA clean task', default=-1, verbose_name='Negative Components')),
                ('casa_smallscalebias', models.FloatField(help_text='See CASA clean task', default=0.6, verbose_name='Small scale bias')),
                ('casa_restoringbeam', models.CharField(null=True, max_length=32, verbose_name='Restoring beam', blank=True)),
                ('casa_cyclefactor', models.FloatField(default=1.5, verbose_name='Cycle factor')),
                ('casa_cyclespeedup', models.FloatField(default=-1, verbose_name='Cycle speed up')),
                ('moresane', models.BooleanField(default=False, verbose_name='Deconvolve with me!')),
                ('moresane_scalecount', models.IntegerField(null=True, blank=True, verbose_name='Scale count', help_text='See MORESANE help')),
                ('moresane_subregion', models.IntegerField(null=True, blank=True, verbose_name='Sub region', help_text='Inner region to deconvolve in pixels')),
                ('moresane_startscale', models.FloatField(default=1, verbose_name='Start scale')),
                ('moresane_stopscale', models.FloatField(default=20, verbose_name='Stop scale')),
                ('moresane_sigmalevel', models.FloatField(help_text='in sigma above noise', default=3, verbose_name='Threshold level')),
                ('moresane_loopgain', models.FloatField(default='0.1', verbose_name='Loop gain')),
                ('moresane_tolerance', models.FloatField(default=0.75, verbose_name='Tolerance')),
                ('moresane_accuracy', models.FloatField(default=1e-06, verbose_name='Accuracy')),
                ('moresane_majorloopmiter', models.IntegerField(default=100, verbose_name='Major loop iterations')),
                ('moresane_minorloopmiter', models.IntegerField(default=50, verbose_name='Minor loop iterations')),
                ('moresane_convmode', models.CharField(default='C', choices=[('C', 'circular'), ('L', 'linear')], max_length=32, verbose_name='Convolution mode')),
                ('moresane_enforcepositivity', models.BooleanField(default=False, verbose_name='Enforce Positivity')),
                ('moresane_edgesupression', models.BooleanField(default=False, verbose_name='Edge Suppression')),
                ('moresane_edgeoffset', models.FloatField(default=0, verbose_name='Edge offset')),
                ('moresane_mfs', models.BooleanField(help_text='Comes with an spi map', default=False, verbose_name='MFS map')),
                ('moresane_spi_dash_sigmalevel', models.FloatField(help_text='In sigma above noise', default=10, verbose_name='spi threshold level')),
                ('state', models.CharField(default='S', choices=[('S', 'scheduled'), ('R', 'running'), ('C', 'crashed'), ('F', 'finished')], max_length=1)),
                ('started', models.DateTimeField(null=True, blank=True)),
                ('finished', models.DateTimeField(null=True, blank=True)),
                ('log', models.FileField(null=True, upload_to='', blank=True)),
                ('console', models.TextField(null=True, blank=True)),
                ('task_id', models.CharField(null=True, max_length=36, blank=True)),
                ('results_uvcov', models.FileField(null=True, upload_to='uvcov', blank=True)),
                ('results_dirty', models.FileField(null=True, upload_to='dirty', blank=True)),
                ('results_model', models.FileField(null=True, upload_to='model', blank=True)),
                ('results_residual', models.FileField(null=True, upload_to='residual', blank=True)),
                ('results_restored', models.FileField(null=True, upload_to='restored', blank=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
    ]
