# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simqueue', '0010_auto_20141112_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='dc_niter',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='dc_nscales',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='dc_operation',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='dc_threshold',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='dc_uservector',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='deconvolve',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='ms_nband',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='ms_write_auto_corr',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='result_dir',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='tdl_conf',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='tdl_section',
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa',
            field=models.BooleanField(verbose_name='Deconvolve with me!', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_cyclefactor',
            field=models.FloatField(verbose_name='Cycle factor', default=1.5),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_cyclespeedup',
            field=models.FloatField(verbose_name='Cycle speed up', default=-1),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_gain',
            field=models.FloatField(verbose_name='Loop Gain', default='0.1', help_text='Clean Loop gain'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_gridmode',
            field=models.CharField(blank=True, choices=[('W', 'widefield'), ('A', 'aprojection')], max_length=32, verbose_name='Grid mode', help_text='A-projection only works JVLA', default='W'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_imagermode',
            field=models.CharField(verbose_name='Imager mode', blank=True, choices=[('C', 'csclean'), ('M', 'mosiac')], default='csclean', max_length=32),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_multiscale',
            field=models.CharField(verbose_name='Multiscale', blank=True, help_text='Deconvolution scales in pixels', null=True, max_length=200),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_negcomponent',
            field=models.FloatField(verbose_name='Negative Components', default=-1, help_text='See CASA clean task'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_niter',
            field=models.IntegerField(verbose_name='NITER', default=1000),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_nterms',
            field=models.IntegerField(verbose_name='NTERMS', default=1, help_text='See CASA clean task'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_psfmode',
            field=models.CharField(verbose_name='PSF mode', default='CL', choices=[('CL', 'clark'), ('CS', 'clarkstokes'), ('H', 'hogbom')], max_length=32),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_reffreq',
            field=models.FloatField(verbose_name='MFS ref Frequency', blank=True, null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_restoringbeam',
            field=models.CharField(verbose_name='Restoring beam', blank=True, null=True, max_length=32),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_smallscalebias',
            field=models.FloatField(verbose_name='Small scale bias', default=0.6, help_text='See CASA clean task'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='casa_threshold',
            field=models.FloatField(verbose_name='Threshold', default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='fluxrange',
            field=models.CharField(verbose_name='Flux range', default='0.001-1', help_text='Flux range in Jy', max_length=32),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='im_robust',
            field=models.FloatField(verbose_name='Robust', default=0, help_text='Briggs robust parameter'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='imager',
            field=models.CharField(verbose_name='Imager', default='LW', choices=[('LW', 'LWIMAGER'), ('WS', 'WSCLEAN'), ('CA', 'CASA')], max_length=32),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='katalog_id',
            field=models.CharField(blank=True, choices=[('NV', 'nvss6deg'), ('S3', 'scubed1deg'), ('K3', '3c147_field'), ('K4', '3c147_field_no_core')], max_length=64, verbose_name='KATALOG', help_text='Choose from our sky catalogs', default='NV'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='lwimager',
            field=models.BooleanField(verbose_name='Deconvolve with me!', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='lwimager_cyclefactor',
            field=models.FloatField(verbose_name='Cycle factor', default=1.5),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='lwimager_cyclespeedup',
            field=models.FloatField(verbose_name='Cycle speed up', default=-1),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='lwimager_gain',
            field=models.FloatField(verbose_name='Loop gain', default=0.1),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='lwimager_niter',
            field=models.IntegerField(verbose_name='NITER', default=1000),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='lwimager_nscales',
            field=models.IntegerField(verbose_name='Scales for MS clean', default=4),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='lwimager_operation',
            field=models.CharField(verbose_name='Clean algorithm', default='C', choices=[('C', 'csclean'), ('H', 'hogbom'), ('D', 'clark'), ('M', 'multiscale')], max_length=32),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='lwimager_stoppointmode',
            field=models.FloatField(verbose_name='Stop point mode,', default=-1),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='lwimager_threshold',
            field=models.FloatField(verbose_name='Clean Threshold', default=0, help_text='In Jy'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='lwimager_uservector',
            field=models.CharField(verbose_name='Clean scales', blank=True, help_text='Comma seperated scales in pixels', null=True, max_length=64),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane',
            field=models.BooleanField(verbose_name='Deconvolve with me!', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_accuracy',
            field=models.FloatField(verbose_name='Accuracy', default=1e-06),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_convmode',
            field=models.CharField(verbose_name='Convolution mode', default='C', choices=[('C', 'circular'), ('L', 'linear')], max_length=32),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_edgeoffset',
            field=models.FloatField(verbose_name='Edge offset', default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_edgesupression',
            field=models.BooleanField(verbose_name='Edge Suppression', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_enforcepositivity',
            field=models.BooleanField(verbose_name='Enforce Positivity', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_loopgain',
            field=models.FloatField(verbose_name='Loop gain', default='0.1'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_majorloopmiter',
            field=models.IntegerField(verbose_name='Major loop iterations', default=100),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_mfs',
            field=models.BooleanField(verbose_name='MFS map', help_text='Comes with an spi map', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_minorloopmiter',
            field=models.IntegerField(verbose_name='Minor loop iterations', default=50),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_scalecount',
            field=models.IntegerField(verbose_name='Scale count', blank=True, help_text='See MORESANE help', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_sigmalevel',
            field=models.FloatField(verbose_name='Threshold level', default=3, help_text='in sigma above noise'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_spi_dash_sigmalevel',
            field=models.FloatField(verbose_name='spi threshold level', default=10, help_text='In sigma above noise'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_startscale',
            field=models.FloatField(verbose_name='Start scale', default=1),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_stopscale',
            field=models.FloatField(verbose_name='Stop scale', default=20),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_subregion',
            field=models.IntegerField(verbose_name='Sub region', blank=True, help_text='Inner region to deconvolve in pixels', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='moresane_tolerance',
            field=models.FloatField(verbose_name='Tolerance', default=0.75),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='ms_start_time',
            field=models.FloatField(verbose_name='Initial hour angle', default=-0.125, help_text='in hours'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='observatory',
            field=models.CharField(choices=[('MK', 'MeerKAT'), ('K7', 'KAT-7'), ('JA', 'JVLA-A')], default='MK', max_length=32),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='radius',
            field=models.FloatField(verbose_name='Radius', blank=True, help_text='Radius of degrees', default=0.5),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='sefd',
            field=models.FloatField(verbose_name='SEFD', blank=True, help_text='System defaults will be used if left blank', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean',
            field=models.BooleanField(verbose_name='Deconvolve with me!', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_beamsize',
            field=models.CharField(verbose_name='Restoring beam size', blank=True, help_text='In arcseconds', null=True, max_length=32),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_cleanborder',
            field=models.FloatField(verbose_name='Clean border', default=5, help_text='In percentage of image width/height'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_gain',
            field=models.FloatField(verbose_name='Minor loop gain', default=0.1),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_joinchannels',
            field=models.BooleanField(verbose_name='Join channels', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_joinpolarizations',
            field=models.BooleanField(verbose_name='Join polarizations', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_mgain',
            field=models.FloatField(verbose_name='Major loop gain', default=0.1),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_multiscale',
            field=models.BooleanField(verbose_name='Multiscale clean', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_multiscale_dash_scale_dash_bias',
            field=models.FloatField(verbose_name='Multi scale bias', default=0.6),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_multiscale_dash_threshold_dash_bias',
            field=models.FloatField(verbose_name='Multi scale threshold bias', default=0.7),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_niter',
            field=models.IntegerField(verbose_name='NITER', default=1000),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_nonegative',
            field=models.BooleanField(verbose_name='No negative', help_text='Do not allow negative components during cleaning', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_smallpsf',
            field=models.BooleanField(verbose_name='Small PSF', help_text='Resize the psf to speed up minor clean iterations', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_stopnegative',
            field=models.BooleanField(verbose_name='Stop on negative', default=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='simulation',
            name='wsclean_threshold',
            field=models.FloatField(verbose_name='Clean Threshold', default=0, help_text='In Jy'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='channelise',
            field=models.FloatField(verbose_name='Image channelise', default=0, help_text='0 means average all, 1 per channel, etc.'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='ds_primary_beam',
            field=models.CharField(choices=[('M', 'MeerKAT-1'), ('N', 'MeerKAT-2'), ('O', 'MeerKAT-3'), ('K', 'KAT-7'), ('W', 'WSRT'), ('J', 'JVLA')], default='M', max_length=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='im_mode',
            field=models.CharField(verbose_name='Imaging mode', default='C', choices=[('C', 'channel'), ('M', 'mfs'), ('V', 'velocity'), ('F', 'frequency')], max_length=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='im_weight_fov',
            field=models.FloatField(verbose_name='Weight FoV', blank=True, help_text='in arcminutes', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='log',
            field=models.FileField(blank=True, upload_to='', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='make_psf',
            field=models.BooleanField(verbose_name='Make PSF', default=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='ms_dec',
            field=models.CharField(verbose_name='Declination', default='-30d0m0s', help_text='in dms', max_length=32),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='ms_dfreq',
            field=models.FloatField(verbose_name='Channel width', default=50000.0, help_text='in kHz'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='ms_freq0',
            field=models.FloatField(verbose_name='Start frequency', default=700, help_text='in MHz'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='ms_hours',
            field=models.FloatField(verbose_name='Synthesis time', default=0.25, help_text='in hours'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='ms_ra',
            field=models.CharField(verbose_name='Right ascension', default='0h0m0s', help_text='in hms', max_length=32),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='results_dirty',
            field=models.FileField(blank=True, upload_to='dirty', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='results_model',
            field=models.FileField(blank=True, upload_to='model', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='results_residual',
            field=models.FileField(blank=True, upload_to='residual', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='results_restored',
            field=models.FileField(blank=True, upload_to='restored', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='results_uvcov',
            field=models.FileField(blank=True, upload_to='uvcov', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='sky_model',
            field=models.FileField(blank=True, upload_to='sky'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='sky_type',
            field=models.CharField(choices=[('T', 'Tigger-LSM'), ('A', 'ASCII'), ('F', 'FITS'), ('S', 'KATALOG')], default='T', max_length=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='state',
            field=models.CharField(choices=[('S', 'scheduled'), ('R', 'running'), ('C', 'crashed'), ('F', 'finished')], default='S', max_length=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='simulation',
            name='vis_noise_std',
            field=models.FloatField(verbose_name='Visibility noise std', default=0, help_text='Generates from SEFD if 0'),
            preserve_default=True,
        ),
    ]
