# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('scheduler', '0006_auto_20160322_1441'), ('scheduler', '0007_auto_20160322_1545'), ('scheduler', '0008_auto_20160322_1549'), ('scheduler', '0009_auto_20160322_1550')]

    dependencies = [
        ('scheduler', '0005_auto_20160301_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='KlikoImage',
        ),
        migrations.RemoveField(
            model_name='klikoimage',
            name='name',
        ),
        migrations.AddField(
            model_name='klikoimage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klikoimage',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='klikoimage',
            name='repository',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klikoimage',
            name='state',
            field=models.CharField(choices=[('N', 'NOT_PULLED'), ('G', 'PULLING'), ('P', 'PULLED'), ('I', 'INVALID'), ('V', 'VALID')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='klikoimage',
            name='tag',
            field=models.CharField(default='latest', max_length=255),
        ),
    ]
