# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20160301_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='KlikoImage',
        ),
    ]
