# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20160322_1441_squashed_0009_auto_20160322_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='docker_image',
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scheduler.KlikoImage'),
            preserve_default=False,
        ),
    ]
