# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20160322_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klikoimage',
            name='name',
        ),
        migrations.AddField(
            model_name='klikoimage',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='klikoimage',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 22, 13, 45, 44, 22716, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klikoimage',
            name='repository',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klikoimage',
            name='state',
            field=models.CharField(choices=[('N', 'NOT_PULLED'), ('G', 'PULLING'), ('P', 'PULLED'), ('I', 'INVALID'), ('V', 'VALID')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='klikoimage',
            name='tag',
            field=models.CharField(default='latest', max_length=255, null=True),
        ),
    ]
