# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20160322_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klikoimage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='klikoimage',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
